# air.toml

# Настройки для перезапуска сервера
[build]
delay = 1000 # Задержка перед перезапуском (в миллисекундах)

# Настройки для мониторинга файлов
[monitor]
paths = ["."] # Директории для мониторинга (можно указать несколько)
exclude_dirs = [] # Исключенные директории из мониторинга
include_exts = ["go", "html", "tmpl", "tpl", "js", "css"] # Расширения файлов для мониторинга
exclude_exts = ["exe", "dll"] # Исключенные расширения файлов из мониторинга